// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcTi7_7om2NOFs5wHKPvQEHLRKLnEMPG0',
    appId: '1:662117121121:android:d220a70cd905de018abe20',
    messagingSenderId: '662117121121',
    projectId: 'memursenindirimler',
    storageBucket: 'memursenindirimler.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM1sUMM8VeQtwfWp5G-Gj0ubzB2tXvASk',
    appId: '1:662117121121:ios:ee5fb3cedfb7fb748abe20',
    messagingSenderId: '662117121121',
    projectId: 'memursenindirimler',
    storageBucket: 'memursenindirimler.firebasestorage.app',
    iosBundleId: 'com.muzaffersahin.memursenIndirimler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM1sUMM8VeQtwfWp5G-Gj0ubzB2tXvASk',
    appId: '1:662117121121:ios:ee5fb3cedfb7fb748abe20',
    messagingSenderId: '662117121121',
    projectId: 'memursenindirimler',
    storageBucket: 'memursenindirimler.firebasestorage.app',
    iosBundleId: 'com.muzaffersahin.memursenIndirimler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3H_skeuh5a12KRR2LmLgdeTVmEQSm5xA',
    appId: '1:662117121121:web:78d03393fc487e248abe20',
    messagingSenderId: '662117121121',
    projectId: 'memursenindirimler',
    authDomain: 'memursenindirimler.firebaseapp.com',
    storageBucket: 'memursenindirimler.firebasestorage.app',
    measurementId: 'G-VKCZ4KQHE1',
  );
}
